#!/bin/python3

import os

title = input("생성될 프로그램 입력 : ")
dic = input("작업 디랙토리 위치 :")
is_bonus = input("bonus 유무(미구현) : ")
src_list = []
files = os.listdir(dic)

for file in files :
	if ".c" in file :
		src_list.append(file)

makefile = open("./Makefile", "w")
makefile.write("CC = cc\n")
makefile.write("CFLAGS = -Wall -Wextra -Werror\n")
makefile.write(f"NAME = {title}\n\n")
makefile.write("SRCS = \\\n")

tab = '\t'
max_length = max(len(file) for file in src_list)
max_length = max_length + 4 - max_length % 4

for i, src in enumerate(src_list) :
	needtap = int((max_length - len(src) + len(src) % 4) / 4)
	makefile.write(f"\t{src}{tab * needtap}")
	if (i == len(src_list) - 1) :
		makefile.write("\n\n")
	else :
		makefile.write("\\\n")

makefile.write("OBJS = $(patsubst %.c,%.o,$(SRCS))\n\n")

makefile.write("all : $(NAME)\n")
makefile.write("\n")
makefile.write("$(NAME) : $(OBJS)\n")
makefile.write("\t$(CC) $(CFLAGS) $(OBJS) -o $(NAME)\n")
makefile.write("\n")
makefile.write("%.o : %.c\n")
makefile.write("\t$(CC) $(CFLAGS) -c $< -o $@\n")
makefile.write("\n")
makefile.write("clean:\n")
makefile.write("\trm -rf $(OBJS)\n")
makefile.write("\n")
makefile.write("fclean: clean\n")
makefile.write("\trm -rf $(NAME)\n")
makefile.write("\n")
makefile.write("re:\n")
makefile.write("\t@make fclean\n")
makefile.write("\t@make all\n")
makefile.write("\n")
makefile.write(".PHONY: all clean fclean re\n")
